.\ Documentation for backlightctl
.\ by daerich (branding is important)

.TH BACKLIGHTCTL 1 2021-06-22 GNU/LINUX
.SH NAME
backlightctl \- control backlightd daemon
.SH SYNOPSIS
.B backlightctl 
[OPTION] [SCALE]
.SH DESCRIPTION
backlightctl pushes new configuration options to backlightd and
signals it to reload.
.SH OPTIONS
.TP
p
.B Print 
current brightness scale in percent
.TP
s
.B Set
current brightness to 
.B SCALE
,where scale is an integer between 10 and 100 (naturally).
.SH FILES
.I /etc/backlightd_d.conf \-  backlightd's configuration file
.SH NOTES
.B Only the first letter of the command is checked.

The rest is ignored(commands resemble "BSD-style")
.SH AUTHORS
.UR https://github.com/daerich/backlightd.git
Written by DaErich and tracked on GitHub
.UE
.SH EXAMPLES
Set brightness to 40%:
.IP
.I backlightctl s 40
.PP
Print brightness:
.IP
.I backlightctl p
.PP
Print help:
.IP
.I backlightctl 
.PP 
or
.IP
.I backlightctl sp
.PP 
or 
.IP
.I backlightctl any unknown words 
